# Generated by Django 4.1.7 on 2023-05-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
