# Generated by Django 4.1.7 on 2023-05-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='featured_products',
        ),
    ]
