# Generated by Django 4.1.7 on 2023-05-18 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
    ]
