# Generated by Django 4.1.7 on 2023-06-05 23:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
