# Generated by Django 4.1.7 on 2023-06-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_remove_productimage_image_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='image_urls',
            field=models.JSONField(default=list),
        ),
    ]
