# Generated by Django 4.1.7 on 2023-05-25 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_alter_orderitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Store.product')),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
            ],
            bases=('Store.product',),
        ),
    ]
