# Generated by Django 4.1.7 on 2023-06-06 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_ordersarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersarchive',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.order'),
        ),
    ]
