# Generated by Django 4.1.7 on 2023-06-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_archivedorder_archivedorderitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
