# Generated by Django 4.1.7 on 2023-06-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotions',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
