# Generated by Django 4.1.7 on 2023-06-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_remove_product_promotions_delete_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedorderitems',
            name='archived_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_items', to='Store.archivedorder'),
        ),
    ]
