# Generated by Django 4.1.7 on 2023-06-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_alter_archivedorderitems_archived_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
