# Generated by Django 4.1.7 on 2023-06-04 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 23, 6, 47, 326572, tzinfo=datetime.timezone.utc)),
        ),
    ]
