# Generated by Django 4.1.7 on 2023-05-21 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2023, 5, 21, 23, 52, 59, 991273, tzinfo=datetime.timezone.utc)),
        ),
    ]
