# Generated by Django 4.1.7 on 2023-06-07 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customuser_member_club_reduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 14, 10, 43, 663033, tzinfo=datetime.timezone.utc)),
        ),
    ]
