# Generated by Django 4.1.7 on 2023-03-28 16:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[0-9]+$')])),
                ('birth_date', models.DateField(default=None, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('city', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=60)),
                ('postal_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='^[0-9]+$')])),
                ('is_student', models.BooleanField(default=False)),
                ('is_member_club', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateField(default=datetime.datetime(2023, 3, 28, 16, 3, 7, 69199, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
