# Generated by Django 4.1.7 on 2023-03-27 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2023, 3, 27, 5, 24, 26, 503763, tzinfo=datetime.timezone.utc)),
        ),
    ]
