# Generated by Django 4.1.7 on 2023-03-28 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2023, 3, 28, 16, 12, 9, 334115, tzinfo=datetime.timezone.utc)),
        ),
    ]
