# Generated by Django 4.1.7 on 2023-03-27 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2023, 3, 27, 5, 45, 26, 516192, tzinfo=datetime.timezone.utc)),
        ),
    ]
