# Generated by Django 4.1.7 on 2023-05-02 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2023, 5, 2, 7, 36, 2, 328730, tzinfo=datetime.timezone.utc)),
        ),
    ]
