# Generated by Django 4.1.7 on 2023-03-27 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_customuser_is_admin_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2023, 3, 27, 6, 2, 5, 845796, tzinfo=datetime.timezone.utc)),
        ),
    ]
