# Generated by Django 4.1.7 on 2023-03-27 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2023, 3, 27, 6, 22, 28, 926267, tzinfo=datetime.timezone.utc)),
        ),
    ]
