# Generated by Django 4.1.7 on 2023-03-28 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2023, 3, 28, 4, 47, 41, 586201, tzinfo=datetime.timezone.utc)),
        ),
    ]
