# Generated by Django 4.1.7 on 2023-05-15 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Favorites', '0002_favorites_favoritesitem_delete_customuser'),
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritesitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.product'),
        ),
    ]
