# Generated by Django 4.1.7 on 2023-06-04 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_remove_product_image_productimage'),
        ('Favorites', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritesitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.product'),
        ),
    ]
