# Generated by Django 4.1.7 on 2023-05-21 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_order_customer_alter_orderitem_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Favorites', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritesitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='favorites',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favoritesitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FavoriteItems', to='Store.product'),
        ),
    ]
