# Generated by Django 4.1.7 on 2023-05-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Favorites', '0004_rename_favorites_favoritesitem_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritesitem',
            name='favorites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to='Favorites.favorites'),
        ),
    ]
